#!/bin/sh

# install dependencies
brew install \
    cmake \
    ctags \
    fzf \
    the_silver_searcher \
    ripgrep \
    astyle

python -m pip install \
	autopep8

npm install -g \
	prettier \
	eslint \
	typescript \
	instant-markdown-d \
	csscomb

# link vim files and install plugins
BASEDIR="$(cd "$( dirname "$0")" && pwd)"
mkdir -p ~/.vim
ln -sf $BASEDIR/.vimrc ~/.vimrc
ln -sf $BASEDIR/.vim/UltiSnips ~/.vim/UltiSnips

#vim +PlugInstall +qall
